language: c++

before_install:
# SDL2
# - curl -O http://www.libsdl.org/release/SDL2-2.0.4.tar.gz
# - tar -xzvf SDL2-2.0.4.tar.gz
# - (cd SDL2-2.0.4 && ./configure && make && sudo make install)
- sudo add-apt-repository -y ppa:team-xbmc/ppa
- sudo apt-get update -qq
- sudo apt-get install -y  libsdl2-dev

dist: trusty

addons:
  apt:
    packages:
     - cmake

script:
 - mkdir build && cmake . -Bbuild && cmake --build build --target SkyGB